@startuml
class QuizQuestion {
    + QuizQuestion()
    + QuizQuestion(question:QuestionDTO)
    + Id : int <<get>> <<set>>
    + QuestionText : string <<get>> <<set>>
    + Position : int <<get>> <<set>>
    + QuizId : int <<get>> <<set>>
    + UpdateFromDto(question:QuestionDTO) : void
}
class "IEntity`1"<T> {
}
class "ICollection`1"<T> {
}
"IEntity`1" "<int>" <|-- QuizQuestion
QuizQuestion o-> "CreatedAt" DateTime
QuizQuestion o-> "Quiz" Quiz
QuizQuestion o-> "Answers<QuizAnswer>" "ICollection`1"
@enduml
