@startuml
class Quiz {
    + Quiz()
    + Quiz(quiz:QuizDTO)
    + Id : int <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Position : int <<get>> <<set>>
    + VideoUrl : string <<get>> <<set>>
    + CourseId : int <<get>> <<set>>
}
class "ICollection`1"<T> {
}
Quiz o-> "CreatedAt" DateTime
Quiz o-> "Course" Course
Quiz o-> "Questions<QuizQuestion>" "ICollection`1"
@enduml
