@startuml
class RefreshToken {
    + Id : int <<get>> <<set>>
    + EncryptedToken : string <<get>> <<set>>
    + <<virtual>> LoginProvider : string <<get>> <<set>>
    + LatestJwtAccessTokenJti : string <<get>> <<set>>
}
RefreshToken --> "ExpiryDate" DateTimeOffset
RefreshToken --> "LatestJwtAccessTokenExpiry" DateTimeOffset
RefreshToken o-> "AppUser" AppUser
@enduml
