@startuml
class UserQuizAttempt {
    + Id : int <<get>> <<set>>
    + UserScore : int <<get>> <<set>>
    + QuizId : int <<get>> <<set>>
    + UserEnrollmentId : int <<get>> <<set>>
}
class "ICollection`1"<T> {
}
UserQuizAttempt o-> "CompletedAt" DateTime
UserQuizAttempt o-> "Quiz" Quiz
UserQuizAttempt o-> "UserEnrollment" UserEnrollment
UserQuizAttempt o-> "UserAnswers<UserAnswer>" "ICollection`1"
@enduml
