@startuml
class GoogleController {
    + GoogleController(options:IOptions<MailingOptions>, userManager:UserManager<AppUser>, loginService:ILoginRegisterService, jwtOptions:IOptions<JwtOptions>)
    + CreateAuthorizationCode() : IActionResult
    + <<async>> GetGmailRefreshTokenCallback(code:string) : Task<IActionResult>
    + Login() : IActionResult
    + <<async>> Callback() : Task<IActionResult>
    + AccessDenied() : IActionResult
}
class "UserManager`1"<T> {
}
ControllerBase <|-- GoogleController
GoogleController --> "_options" MailingOptions
GoogleController --> "_userManager<AppUser>" "UserManager`1"
GoogleController --> "_loginService" ILoginRegisterService
GoogleController --> "_jwtOptions" JwtOptions
@enduml
