@startuml
class TagsController {
    + TagsController(unitOfWork:IUnitOfWork)
    + <<async>> GetAllTags() : Task<IActionResult>
    + <<async>> AddTag(tag:string) : Task<IActionResult>
    + <<async>> GetTagByValue(value:string) : Task<IActionResult>
    + <<async>> EditTag(id:int, newValue:string) : Task<IActionResult>
}
ControllerBase <|-- TagsController
TagsController --> "_unitOfWork" IUnitOfWork
@enduml
