@startuml
class ModifyingLatestJWTAccessTokenToJti <<partial>> {
    # <<override>> Up(migrationBuilder:MigrationBuilder) : void
    # <<override>> Down(migrationBuilder:MigrationBuilder) : void
}
Migration <|-- ModifyingLatestJWTAccessTokenToJti
@enduml
