@startuml
class MakingNormalizedEmailNonUnique <<partial>> {
    # <<override>> Up(migrationBuilder:MigrationBuilder) : void
    # <<override>> Down(migrationBuilder:MigrationBuilder) : void
}
Migration <|-- MakingNormalizedEmailNonUnique
@enduml
