@startuml
class UpdatingCoursesAddingRequirement <<partial>> {
    # <<override>> Up(migrationBuilder:MigrationBuilder) : void
    # <<override>> Down(migrationBuilder:MigrationBuilder) : void
}
Migration <|-- UpdatingCoursesAddingRequirement
@enduml
