@startuml
class UpdatingUserEnrollmentIndex <<partial>> {
    # <<override>> Up(migrationBuilder:MigrationBuilder) : void
    # <<override>> Down(migrationBuilder:MigrationBuilder) : void
}
Migration <|-- UpdatingUserEnrollmentIndex
@enduml
