@startuml
class AddingTotalStagesToEnrollment <<partial>> {
    # <<override>> Up(migrationBuilder:MigrationBuilder) : void
    # <<override>> Down(migrationBuilder:MigrationBuilder) : void
}
Migration <|-- AddingTotalStagesToEnrollment
@enduml
