@startuml
class AppUserDTO {
    + Id : int <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + UserName : string <<get>> <<set>>
    + PhoneNumber : string? <<get>> <<set>>
    + PhoneRegionCode : string? <<get>> <<set>>
    + Banned : bool <<get>> <<set>>
    + IsExternal : bool <<get>> <<set>>
}
AppUserDTO o-> "Image" ImageMetadata
@enduml
