@startuml
class InstructorController {
    + InstructorController(unitOfWork:IUnitOfWork, userManager:UserManager<AppUser>, cloudinary:ICloudinaryService, uploadingService:IUploadingService, coursesService:ICoursesService)
    + <<async>> GetInstructorCourses(instructorId:int, index:int) : Task<IActionResult>
    + <<async>> GetCourseStatistics(courseId:int) : Task<IActionResult>
    + <<async>> AddCourse(course:RegisterCourseRequest) : Task<IActionResult>
    + <<async>> EditCourse(course:EditCourseRequest) : Task<IActionResult>
    + <<async>> EditCourseImage(image:IFormFile, courseId:int, instructorId:int) : Task<IActionResult>
    + <<async>> GetCourseWithQuizes(courseId:int) : Task<IActionResult>
    + <<async>> DeleteCourse(req:DeleteCourseRequest) : Task<IActionResult>
}
class "UserManager`1"<T> {
}
ControllerBase <|-- InstructorController
InstructorController --> "_userManager<AppUser>" "UserManager`1"
InstructorController --> "_coursesService" ICoursesService
@enduml
