@startuml
class AuthenticatedPayload {
    Email : string <<get>> <<set>>
    Name : string <<get>> <<set>>
    ImageUrl : string <<get>> <<set>>
    UniqueId : string <<get>> <<set>>
}
AuthenticatedPayload --> "DeviceInfo" required
@enduml
