@startuml
interface ICloudinaryService {
    + {static} DefaultUserImagePublicId : string <<get>>
    + {static} DefaultCourseImagePublicId : string <<get>>
    GetImageUrl(publicId:string) : string
    GetProfileImage(publicId:string) : string
    GetPDF(publicId:string) : string
}
class CloudinaryService {
    + CloudinaryService(cloudinary:Cloudinary)
    + GetImageUrl(publicId:string) : string
    + GetProfileImage(publicId:string) : string
    + GetPDF(publicId:string) : string
}
ICloudinaryService <|-- CloudinaryService
CloudinaryService --> "_cloudinary" Cloudinary
@enduml
