@startuml
class "PaginatedList`1"<T> {
    + PageIndex : int <<get>>
    + PageSize : int <<get>>
    + TotalCount : int <<get>>
    + TotalPages : int <<get>>
    - PaginatedList(source:IEnumerable<T>, pageIndex:int, pageSize:int, totalCount:int)
    + HasPreviousPage : bool <<get>>
    + HasNextPage : bool <<get>>
    + {static} <<async>> CreateAsync(source:IQueryable<T>, pageIndex:int, pageSize:int) : Task<PaginatedList<T>>
    + {static} Create(source:IQueryable<T>, pageIndex:int, pageSize:int) : PaginatedList<T>
}
class "List`1"<T> {
}
"List`1" "<T>" <|-- "PaginatedList`1"
@enduml
