@startuml
class "ServiceResult`1"<T> {
    + IsSuccess : bool <<get>>
    + Data : T? <<get>>
    + Error : string? <<get>>
    - ServiceResult(isSuccess:bool, data:T?, error:string?)
    + {static} Success(data:T) : ServiceResult<T>
    + {static} Failure(error:string) : ServiceResult<T>
    + {static} Failure(errors:ICollection<string>) : ServiceResult<T>
}
@enduml
