@startuml
interface IUploadingService {
    UploadImageAsync(imageUrl:string, imageName:string, type:CloudinaryType) : Task<FileHash?>
    UploadImageAsync(stream:Stream, imageName:string, type:CloudinaryType) : Task<FileHash?>
}
class UploadingService {
    + UploadingService(cloudinary:Cloudinary, hashingService:IHashingService)
    + {static} IsValidImageType(image:IFormFile?, maxSize:long) : bool
    + <<async>> UploadImageAsync(stream:Stream, imageName:string, type:CloudinaryType) : Task<FileHash?>
    - <<async>> UploadAsync(image:Stream, imageName:string, type:CloudinaryType) : Task<string?>
    + <<async>> UploadImageAsync(imageUrl:string, imageName:string, type:CloudinaryType) : Task<FileHash?>
    - <<async>> UploadAsync(imageUrl:string, imageName:string, type:CloudinaryType) : Task<string?>
    - <<async>> GetFileStreamAsync(publicId:string) : Task<Stream?>
}
IUploadingService <|-- UploadingService
UploadingService --> "_cloudinary" Cloudinary
UploadingService --> "_hashingService" IHashingService
@enduml
