@startuml ClassDiagram
!include .\\GraduationProject\StartupConfigurations\AuthenticationServiceConfiguration.puml
!include .\\GraduationProject\StartupConfigurations\DependencyInjectionConfig.puml
!include .\\GraduationProject\StartupConfigurations\JwtOptions.puml
!include .\\GraduationProject\StartupConfigurations\MailingOptions.puml
!include .\\GraduationProject\StartupConfigurations\RateLimiterConfig.puml
!include .\\GraduationProject\StartupConfigurations\VqaApiKeyOption.puml
!include .\\GraduationProject\API\Controllers\AdminController.puml
!include .\\GraduationProject\API\Controllers\AuthenticationController.puml
!include .\\GraduationProject\API\Controllers\CoursesController.puml
!include .\\GraduationProject\API\Controllers\GoogleController.puml
!include .\\GraduationProject\API\Controllers\InstructorController.puml
!include .\\GraduationProject\API\Controllers\RolesController.puml
!include .\\GraduationProject\API\Controllers\StudentController.puml
!include .\\GraduationProject\API\Controllers\TagsController.puml
!include .\\GraduationProject\API\Controllers\TokenController.puml
!include .\\GraduationProject\API\Controllers\UsersController.puml
!include .\\GraduationProject\API\Controllers\VqaController.puml
!include .\\GraduationProject\API\Requests\ConfirmEmailRequest.puml
!include .\\GraduationProject\API\Requests\EditCourseRequest.puml
!include .\\GraduationProject\API\Requests\LoginCustomRequest.puml
!include .\\GraduationProject\API\Requests\RegisterCourseRequest.puml
!include .\\GraduationProject\API\Requests\RegisterCustomRequest.puml
!include .\\GraduationProject\API\Requests\RoleRequest.puml
!include .\\GraduationProject\API\Requests\StudentEnrollmentRequest.puml
!include .\\GraduationProject\API\Requests\UpdateEmailRequest.puml
!include .\\GraduationProject\API\Requests\UpdatePasswordRequest.puml
!include .\\GraduationProject\API\Requests\UpdateUsernameRequest.puml
!include .\\GraduationProject\API\Responses\AuthenticatedPayload.puml
!include .\\GraduationProject\API\Responses\DetailedCourseResponse.puml
!include .\\GraduationProject\API\Responses\ErrorResponse.puml
!include .\\GraduationProject\API\Responses\GoogleProfileResponse.puml
!include .\\GraduationProject\API\Responses\LoginResponse.puml
!include .\\GraduationProject\API\Responses\PaginatedResponse.puml
!include .\\GraduationProject\API\Responses\RefreshTokenResponse.puml
!include .\\GraduationProject\API\Responses\SuccessResponse.puml
!include .\\GraduationProject\API\Responses\VqaResponse.puml
!include .\\GraduationProject\Application\Services\CloudinaryService.puml
!include .\\GraduationProject\Application\Services\CourseGenerator.puml
!include .\\GraduationProject\Application\Services\EncryptionService.puml
!include .\\GraduationProject\Application\Services\FileHashingService.puml
!include .\\GraduationProject\Application\Services\GmailServiceHelper.puml
!include .\\GraduationProject\Application\Services\JwtTokenService.puml
!include .\\GraduationProject\Application\Services\LoginRegisterService.puml
!include .\\GraduationProject\Application\Services\PaginatedList.puml
!include .\\GraduationProject\Application\Services\PhoneNumberService.puml
!include .\\GraduationProject\Application\Services\RefreshTokenService.puml
!include .\\GraduationProject\Application\Services\ServiceResult.puml
!include .\\GraduationProject\Application\Services\TokenBlacklistService.puml
!include .\\GraduationProject\Application\Services\UploadingService.puml
!include .\\GraduationProject\Application\Services\UserService.puml
!include .\\GraduationProject\Application\Services\VqaService.puml
!include .\\GraduationProject\Common\Extensions\AppUserExtension.puml
!include .\\GraduationProject\Common\Extensions\CloudinaryExtensions.puml
!include .\\GraduationProject\Common\Extensions\CourseExtension.puml
!include .\\GraduationProject\Common\Middlewares\CheckingRefreshTokenAfterAuthorizationMiddleware.puml
!include .\\GraduationProject\Common\Middlewares\TokenBlacklistMiddleware.puml
!include .\\GraduationProject\Domain\DTOs\AppUserDTO.puml
!include .\\GraduationProject\Domain\DTOs\CourseDTO.puml
!include .\\GraduationProject\Domain\DTOs\CourseStatistics.puml
!include .\\GraduationProject\Domain\DTOs\EnrollmentDTO.puml
!include .\\GraduationProject\Domain\DTOs\ImageMetadata.puml
!include .\\GraduationProject\Domain\DTOs\IPostitionable.puml
!include .\\GraduationProject\Domain\DTOs\QuestionDTO.puml
!include .\\GraduationProject\Domain\DTOs\QuizAnswerDTO.puml
!include .\\GraduationProject\Domain\DTOs\QuizDTO.puml
!include .\\GraduationProject\Domain\DTOs\TagDTO.puml
!include .\\GraduationProject\Domain\DTOs\UserAnswerDTO.puml
!include .\\GraduationProject\Domain\DTOs\UserQuizAttemptDTO.puml
!include .\\GraduationProject\Domain\Enums\CloudinaryType.puml
!include .\\GraduationProject\Domain\Models\AppUser.puml
!include .\\GraduationProject\Domain\Models\Course.puml
!include .\\GraduationProject\Domain\Models\FileHash.puml
!include .\\GraduationProject\Domain\Models\Quiz.puml
!include .\\GraduationProject\Domain\Models\QuizAnswer.puml
!include .\\GraduationProject\Domain\Models\QuizQuestion.puml
!include .\\GraduationProject\Domain\Models\RefreshToken.puml
!include .\\GraduationProject\Domain\Models\Role.puml
!include .\\GraduationProject\Domain\Models\Tag.puml
!include .\\GraduationProject\Domain\Models\UserAnswer.puml
!include .\\GraduationProject\Domain\Models\UserEnrollment.puml
!include .\\GraduationProject\Domain\Models\UserQuizAttempt.puml
!include .\\GraduationProject\Domain\ValidationAttributes\JsonModelBinder.puml
!include .\\GraduationProject\Domain\ValidationAttributes\NotEmptyCollectionAttribute.puml
!include .\\GraduationProject\Domain\ValidationAttributes\NotEmptyOrWhiteSpaceAttribute.puml
!include .\\GraduationProject\Domain\ValidationAttributes\UniquePostitionAttribute.puml
!include .\\GraduationProject\Infrastructure\Data\AppDbContext.puml
!include .\\GraduationProject\Infrastructure\Data\MyDbFunctions.puml
!include .\\GraduationProject\Infrastructure\Data\UnitOfWork.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\AppUserConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\CoursesConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\FileHashConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\QuizAnswerConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\QuizConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\QuizQuestionConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\RefreshTokenConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\RolesConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\TagsConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\UserAnswerConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\UserEnrollmentConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Configuration\UserQuizAttemptConfiguration.puml
!include .\\GraduationProject\Infrastructure\Data\Repositories\CoursesRepository.puml
!include .\\GraduationProject\Infrastructure\Data\Repositories\EnrollmentRepository.puml
!include .\\GraduationProject\Infrastructure\Data\Repositories\FileHashRepository.puml
!include .\\GraduationProject\Infrastructure\Data\Repositories\QuizRepository.puml
!include .\\GraduationProject\Infrastructure\Data\Repositories\Repository.puml
!include .\\GraduationProject\Infrastructure\Data\Repositories\TagsRepository.puml
!include .\\GraduationProject\Infrastructure\Data\Repositories\TokenRepository.puml
!include .\\GraduationProject\Infrastructure\Data\Repositories\UserLoginRepo.puml
!include .\\GraduationProject\Infrastructure\Data\Repositories\UsersRepository.puml
@enduml
