@startuml
top to bottom direction
skinparam ranksep 100
skinparam nodesep 20

!include API/Controllers/AdminController.puml
!include API/Controllers/AuthenticationController.puml
!include API/Controllers/CoursesController.puml
!include API/Controllers/GoogleController.puml
!include API/Controllers/GrammarCorrectionController.puml
!include API/Controllers/InstructorController.puml
!include API/Controllers/ReviewController.puml
!include API/Controllers/RolesController.puml
!include API/Controllers/StudentController.puml
!include API/Controllers/TagsController.puml
!include API/Controllers/TextToSpeechController.puml
!include API/Controllers/TokenController.puml
!include API/Controllers/UsersController.puml
!include API/Controllers/VqaController.puml

!include Application/Services/AdminService.puml
!include Application/Services/AuthenticationService.puml
!include Application/Services/CloudinaryService.puml
!include Application/Services/CoursesService.puml
!include Application/Services/EncryptionService.puml
!include Application/Services/FileHashingService.puml
!include Application/Services/GmailServiceHelper.puml
!include Application/Services/JwtTokenService.puml
!include Application/Services/MediaValidator.puml
!include Application/Services/PaginatedList.puml
!include Application/Services/PhoneNumberService.puml
!include Application/Services/RefreshTokenService.puml
!include Application/Services/ReviewService.puml
!include Application/Services/ServiceResult.puml
!include Application/Services/StudentService.puml
!include Application/Services/TokenBlacklistService.puml
!include Application/Services/UploadingService.puml
!include Application/Services/UserService.puml

!include Domain/DTOs/AppUserDTO.puml
!include Domain/DTOs/CourseDTO.puml
!include Domain/DTOs/CourseStatistics.puml
!include Domain/DTOs/EnrollmentDTO.puml
!include Domain/DTOs/ImageMetadata.puml
!include Domain/DTOs/IPostitionable.puml
!include Domain/DTOs/LoginWithCookies.puml
!include Domain/DTOs/QuestionDTO.puml
!include Domain/DTOs/QuizAnswerDTO.puml
!include Domain/DTOs/QuizDTO.puml
!include Domain/DTOs/QuizQuestionAnswerIds.puml
!include Domain/DTOs/RatingStatus.puml
!include Domain/DTOs/ReviewDTO.puml
!include Domain/DTOs/ReviewItemDTO.puml
!include Domain/DTOs/TagDTO.puml
!include Domain/DTOs/UserAnswerDTO.puml
!include Domain/DTOs/UserQuizAttemptDTO.puml
!include Domain/Enums/CloudinaryType.puml
!include Domain/Models/AppUser.puml
!include Domain/Models/Course.puml
!include Domain/Models/FileHash.puml
!include Domain/Models/IEntity.puml
!include Domain/Models/Quiz.puml
!include Domain/Models/QuizAnswer.puml
!include Domain/Models/QuizQuestion.puml
!include Domain/Models/RefreshToken.puml
!include Domain/Models/Review.puml
!include Domain/Models/Role.puml
!include Domain/Models/Tag.puml
!include Domain/Models/UserAnswer.puml
!include Domain/Models/UserEnrollment.puml
!include Domain/Models/UserQuizAttempt.puml

!include Infrastructure/Data/AppDbContext.puml
!include Infrastructure/Data/DictionaryUnitOfWork.puml
!include Infrastructure/Data/MyDbFunctions.puml
!include Infrastructure/Data/UnitOfWork.puml

!include Application/Services/HttpClientServices/GrammarCorrectionService.puml
!include Application/Services/HttpClientServices/TextToSpeechService.puml
!include Application/Services/HttpClientServices/VqaService.puml
!include Application/Services/Interfaces/IAdminService.puml
!include Application/Services/Interfaces/IAuthenticationService.puml
!include Application/Services/Interfaces/ICloudinaryService.puml
!include Application/Services/Interfaces/ICoursesService.puml
!include Application/Services/Interfaces/IEncryptionService.puml
!include Application/Services/Interfaces/IGmailServiceHelper.puml
!include Application/Services/Interfaces/IGrammarCorrectionService.puml
!include Application/Services/Interfaces/IHashingService.puml
!include Application/Services/Interfaces/IJwtTokenService.puml
!include Application/Services/Interfaces/IMediaValidator.puml
!include Application/Services/Interfaces/IRefreshTokenService.puml
!include Application/Services/Interfaces/IReviewService.puml
!include Application/Services/Interfaces/IStudentService.puml
!include Application/Services/Interfaces/ITextToSpeechService.puml
!include Application/Services/Interfaces/ITokenBlacklistService.puml
!include Application/Services/Interfaces/IUploadingService.puml
!include Application/Services/Interfaces/IUserService.puml
!include Application/Services/Interfaces/IVqaService.puml

!include Infrastructure/Data/Interfaces/IDictionaryUnitOfWork.puml
!include Infrastructure/Data/Interfaces/IUnitOfWork.puml
!include Infrastructure/Data/Repositories/CoursesRepository.puml
!include Infrastructure/Data/Repositories/EnrollmentRepository.puml
!include Infrastructure/Data/Repositories/FileHashRepository.puml
!include Infrastructure/Data/Repositories/QuizQuestionRepository.puml
!include Infrastructure/Data/Repositories/QuizRepository.puml
!include Infrastructure/Data/Repositories/ReviewsRepository.puml
!include Infrastructure/Data/Repositories/TagsRepository.puml
!include Infrastructure/Data/Repositories/TokenRepository.puml
!include Infrastructure/Data/Repositories/UserLoginRepo.puml
@enduml