@startuml
class GmailServiceHelper {
    - <<readonly>> _applicationName : string = "Engenetic"
    + GmailServiceHelper(options:IOptions<MailingOptions>, userManager:UserManager<AppUser>)
    + <<async>> SendEmailAsync(to:string, subject:string, body:string) : Task
    - CreateEmail(to:string, from:string, subject:string, body:string) : Message
}
class "UserManager`1"<T> {
}
IGmailServiceHelper <|-- GmailServiceHelper
GmailServiceHelper --> "_options" MailingOptions
GmailServiceHelper --> "_userManager<AppUser>" "UserManager`1"
@enduml
