@startuml
class UserQuizAttemptDTO {
    + UserId : int <<get>> <<set>>
    + EnrollmentId : int <<get>> <<set>>
    + QuizId : int <<get>> <<set>>
    + IsPassed : bool <<get>> <<set>> = false
    + Score : string <<get>> <<set>>
}
class "List`1"<T> {
}
UserQuizAttemptDTO o-> "UserAnswers<UserAnswerDTO>" "List`1"
@enduml
