@startuml
class "PaginatedResponse`1"<T> {
    + TotalPages : int <<get>> <<init>>
    + TotalItems : int <<get>> <<init>>
    + CurrentlyViewing : string <<get>> <<init>>
    + PaginatedResponse(list:PaginatedList<T>)
}
class "PaginatedList`1"<T> {
}
"PaginatedResponse`1" --> "PaginatedList<T>" "PaginatedList`1"
@enduml
