@startuml
class Course {
    + Course()
    + Course(course:RegisterCourseRequest, tags:List<Tag>, hash:FileHash)
    + Id : int <<get>> <<set>>
    + hidden : bool <<get>> <<set>>
    + Code : string? <<get>> <<set>>
    + Title : string <<get>> <<set>>
    + Description : string <<get>> <<set>>
    + Requirements : string <<get>> <<set>>
    + Stages : int <<get>> <<set>>
    + AverageRating : double <<get>> <<set>>
    + InstructorId : int <<get>> <<set>>
    + HashId : int <<get>> <<set>>
    + UpdateFromRequest(course:EditCourseRequest) : void
}
class "IEntity`1"<T> {
}
class "ICollection`1"<T> {
}
"IEntity`1" "<int>" <|-- Course
Course o-> "CreatedAt" DateTime
Course o-> "Instructor" AppUser
Course o-> "FileHash" FileHash
Course o-> "Quizes<Quiz>" "ICollection`1"
Course o-> "Enrollments<UserEnrollment>" "ICollection`1"
Course o-> "Tags<Tag>" "ICollection`1"
Course o-> "Reviews<Review>" "ICollection`1"
@enduml
